GET http://localhost:8080/dev/all

###

POST http://localhost:8080/dev/new
Content-Type: application/json

{
    "message": "Test using routing!"
}

###

GET http://localhost:8080/dev/3

###

DELETE http://localhost:8080/dev/0/delete

###

DELETE http://localhost:8080/dev/delete/all